name: docs
channels:
  - conda-forge
  - SBMLTeam
  - openbabel
  - defaults
dependencies:
  - pip
  - python>=3.6.4
  - sphinx
  - openbabel
  - pip:
    - cement
    - enum34
    - git+https://github.com/KarrLab/obj_model.git#egg=obj_model-0.0.5
    - natsort
    - networkx
    - python_libsbml >= 5.16.0
    - setuptools
    - six
    - git+https://github.com/KarrLab/wc_kb.git#egg=wc_kb-0.0.1
    - git+https://github.com/KarrLab/wc_utils.git#egg=wc_utils-0.0.1a5

    - configparser
    - sphinx_rtd_theme
    - robpol86_sphinxcontrib_googleanalytics
    - sphinxcontrib_bibtex
    - sphinxcontrib_spelling
